# Generated by Django 3.2.4 on 2021-06-26 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='名称')),
                ('authur', models.CharField(default='无', max_length=100, verbose_name='作者')),
                ('category', models.IntegerField(default=0, verbose_name='类别')),
                ('label', models.IntegerField(default=0, verbose_name='标签')),
                ('plate', models.IntegerField(default=0, verbose_name='板块')),
                ('introduction', models.TextField(default='无', verbose_name='简介')),
                ('is_look_count', models.IntegerField(default=0, help_text='记录书本被点击的次数', verbose_name='点击次数')),
                ('content', models.TextField(verbose_name='内容')),
                ('url', models.URLField(verbose_name='URL')),
                ('crawling_status', models.BooleanField(default=False, help_text='用于判断后台脚本是否已爬取内容', verbose_name='下载状态')),
                ('index', models.IntegerField(default=0, verbose_name='索引')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['index', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='名称')),
                ('authur', models.CharField(default='无', max_length=100, verbose_name='作者')),
                ('category', models.IntegerField(default=0, verbose_name='类别')),
                ('label', models.IntegerField(default=0, verbose_name='标签')),
                ('plate', models.IntegerField(default=0, verbose_name='板块')),
                ('introduction', models.TextField(default='无', verbose_name='简介')),
                ('is_look_count', models.IntegerField(default=0, help_text='记录书本被点击的次数', verbose_name='点击次数')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '合集',
                'verbose_name_plural': '合集',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='访问人')),
            ],
            options={
                'verbose_name': 'sis001网站访问历史',
                'verbose_name_plural': 'sis001网站访问历史',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CollectionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='个人点击次数')),
                ('collect', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xiaosuo.collection', verbose_name='合集')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='访问人')),
            ],
            options={
                'verbose_name': '用户合集状态',
                'verbose_name_plural': '用户合集状态',
                'ordering': ['count', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ChapterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='个人点击次数')),
                ('dow_code', models.BooleanField(default=False, help_text='用于判断用户是否使用脚本下载过该章节', verbose_name='下载状态')),
                ('look_code', models.FloatField(blank=True, default=None, null=True, verbose_name='章节观看进度')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xiaosuo.chapter', verbose_name='章节')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='访问人')),
            ],
            options={
                'verbose_name': '用户章节观看状态',
                'verbose_name_plural': '用户章节观看状态',
                'ordering': ['count', '-date_joined'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xiaosuo.collection', verbose_name='合集'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
    ]
