# Generated by Django 3.2.4 on 2021-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaosuo', '0005_auto_20210630_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['collection', 'index', '-date_joined'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='collectioncount',
            options={'ordering': ['count', '-date_joined'], 'verbose_name': '用户合集状态（前端-书架）', 'verbose_name_plural': '用户合集状态（前端-书架）'},
        ),
        migrations.AddField(
            model_name='collectioncount',
            name='addbook',
            field=models.BooleanField(default=False, help_text='判断个人看书页面是否将书加入书架', verbose_name='是否加入书架'),
        ),
        migrations.AlterField(
            model_name='collectioncount',
            name='collect',
            field=models.BooleanField(default=False, help_text='判断油猴插件界面是否保存', verbose_name='是否加入收藏'),
        ),
    ]
