# Generated by Django 3.2.4 on 2021-06-30 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xiaosuo', '0006_auto_20210630_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioncount',
            options={'ordering': ['count', '-date_joined'], 'verbose_name': '用户与合集状态', 'verbose_name_plural': '用户与合集状态'},
        ),
        migrations.CreateModel(
            name='UserToVisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('lishi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xiaosuo.visithistory', verbose_name='访问网址')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='访问人')),
            ],
            options={
                'verbose_name': '用户与网址状态',
                'verbose_name_plural': '用户与网址状态',
                'ordering': ['-date_joined'],
            },
        ),
    ]
