# Generated by Django 3.2.4 on 2021-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaosuo', '0010_auto_20210703_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptercode',
            name='end_code',
            field=models.BooleanField(default=False, verbose_name='是否已观看完毕'),
        ),
    ]
