# Generated by Django 3.2.4 on 2021-07-04 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xiaosuo', '0011_chaptercode_end_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptercode',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='访问人'),
        ),
    ]
