# Generated by Django 3.2.4 on 2021-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaosuo', '0014_collectioncount_yikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptercode',
            name='look_code',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='章节观看进度'),
        ),
    ]
