# Generated by Django 3.2.4 on 2022-02-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaosuo', '0015_alter_chaptercode_look_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['crawling_status', 'collection', 'index', '-date_joined'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='chaptercode',
            options={'ordering': ['count', '-date_joined'], 'verbose_name': '用户与章节状态（个人进度）', 'verbose_name_plural': '用户与章节状态（个人进度）'},
        ),
        migrations.AlterModelOptions(
            name='collectioncount',
            options={'ordering': ['count', '-date_joined'], 'verbose_name': '用户与书籍状态', 'verbose_name_plural': '用户与书籍状态'},
        ),
        migrations.AlterModelOptions(
            name='usertovisithistory',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户与sis001访问历史', 'verbose_name_plural': '用户与sis001访问历史'},
        ),
        migrations.AlterModelOptions(
            name='visithistory',
            options={'ordering': ['-date_joined'], 'verbose_name': '所有访问sis001的历史', 'verbose_name_plural': '所有访问sis001的历史'},
        ),
        migrations.AddField(
            model_name='collection',
            name='img',
            field=models.ImageField(blank=True, default='img/book.png', null=True, upload_to='book_img/%Y/%m/%d', verbose_name='封面'),
        ),
    ]
