# Generated by Django 3.2.4 on 2022-02-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaosuo', '0017_collectioncount_jindu'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='bk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xiaosuo.plate', verbose_name='板块'),
        ),
    ]
